INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Verde', 'Um sapinho verde pequeno', '100.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Vermelho', 'Um sapinho vermelho pequeno', '500.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Azul', 'Um sapinho azul pequeno', '20.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Verde', 'Um sapinho verde pequeno', '250.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Vermelho', 'Um sapinho vermelho pequeno', '35.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Azul', 'Um sapinho azul pequeno', '69.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Verde', 'Um sapinho verde pequeno', '24.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Vermelho', 'Um sapinho vermelho pequeno', '1100.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Sapinho Azul', 'Um sapinho azul pequeno', '400.00');
